name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: true
      matrix:
        php: [8.5]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install dependencies
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: ./vendor/bin/pest --coverage --coverage-text --compact
